/**
 * Generated from the FastAPI OpenAPI schema. Do not edit by hand.
 *
 * Regenerate with: pnpm --filter @tcg/web gen:api-types
 * See docs/adr/0001-language-boundaries-in-the-monorepo.md.
 */

export interface paths {
    "/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start an analysis
         * @description Starts an analysis and, if the caller has no live session, opens one. No login and no registration: V1 identifies a user by an anonymous session token only (spec §53), returned in an HTTP-only cookie that every later call to this analysis must carry. A cookie naming a session that has expired or never existed is not an error — a new session is opened. Nothing about the caller is recorded.
         */
        post: operations["start_analysis_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the state of one analysis
         * @description Returns the analysis, provided the caller's session cookie is the session that started it. An identifier that names nothing, an analysis belonging to another session, a missing cookie and an expired one all answer 404 with the same body, so this endpoint cannot be used to discover which analyses exist.
         */
        get: operations["read_one_analysis_analyses__analysis_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/confirm-card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm which card the analysis is of
         * @description Records the card the user has confirmed they are holding (spec §20) and moves the analysis on from `awaiting_confirmation`.
         *
         *     **The card is resolved against the catalog before it is written.** The identifier arrives from a client and is therefore not trusted (spec §55); one that names no card is refused with the same `card_not_identified` that `GET /cards/{id}` answers with.
         *
         *     Only an analysis waiting for a confirmation can take one, and there is no way back: spec §65's states move forwards only, so confirming twice — or confirming a different card afterwards — is a 409. A card chosen in error is corrected by starting a new analysis.
         */
        post: operations["confirm_card_analyses__analysis_id__confirm_card_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload one side of the card
         * @description Accepts one photograph as the request body — the raw image bytes, not a multipart form. The `side` says which view of the card it is; a second upload for the same side replaces the first, so a retake is a correction rather than an extra image.
         *
         *     **The file is validated by its content, never by what the request claims** (spec §55). It must be a JPEG or a PNG, must be within the byte and pixel limits this deployment is configured with, and must decode. Personal metadata — EXIF, including GPS — is removed before anything is stored, and the storage location is generated by the server: no filename is accepted, so none can influence it.
         *
         *     The analysis moves to `uploading` on the first photograph and to `uploaded` once both sides have arrived, which is the state `POST /analyses/{id}/run` requires.
         */
        post: operations["upload_image_analyses__analysis_id__images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyses/{analysis_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run an analysis
         * @description Hands the analysis to a background worker and returns immediately (spec §8, §65): image processing and inference take far longer than an HTTP request should. The response says `queued`, which is an acknowledgement rather than a state — poll `GET /analyses/{id}` to see where the analysis has got to.
         *
         *     Only an analysis whose images have arrived can be run; spec §18's pipeline begins with them. Running one twice is safe: the worker claims the analysis with a conditional update, so a second job finds nothing to do rather than repeating the first.
         */
        post: operations["run_one_analysis_analyses__analysis_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find cards in the catalog
         * @description Searches the canonical catalog so a user can find the card in their hand. Every filter is optional and they are ANDed; an empty query browses the catalog. `text` matches a fragment of the printed name without regard to case, and works for Japanese. `card_number` matches as a prefix of the printed number's numerator, so `25`, `025` and `025/165` all find the card printed `025/165`. Results are ordered by `(set_code, card_number, variant, id)` — a total order, so paging neither drops nor duplicates a row. Nothing matching is an empty page, never a 404. No prices, and no images (ADR 0004).
         */
        get: operations["search_cards_cards_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the canonical detail for one card
         * @description Returns everything the catalog records about one card — spec §6's Card block, apart from identification confidence, which belongs to an analysis rather than to a catalog record. No card images: ADR 0004 imports none, so the only card images this product shows are the user's own uploads. No prices: `GET /cards/{id}/market` is M4.
         */
        get: operations["read_card_cards__card_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cards/{card_id}/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one card's market prices from a snapshot
         * @description Spec §64's market endpoint. Returns the ungraded price and every grade every supported company can issue, each with spec §38's `price_confidence` and `price_age` — **per price**, because a fresh raw price and a six-week-old PSA 10 price on the same card is the gap that matters. Served entirely from a market snapshot: no provider is called during a request (spec §37), and the snapshot's `data_version` is returned so a result can be shown for the date it describes rather than as today's. A price this snapshot does not hold is `null` rather than absent, and is never filled in from another company or interpolated. Pass `?snapshot_id=` to re-read exactly what a past analysis saw. No price history and no fees: the first is out under ADR 0006, the second is spec §45's user-configured economic input.
         */
        get: operations["read_card_market_cards__card_id__market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/catalog/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report the card catalog version in use
         * @description Returns the card catalog version this deployment is serving — spec §57's `card_database_version`, one of the seven fields an analysis records so it can be re-derived. Reads the database, which is why it is a separate endpoint from `/health`.
         */
        get: operations["read_catalog_version_catalog_version_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/grading-companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the grading companies and their grade scales
         * @description Spec §64's grading endpoint. Returns every supported company with the exact grades it can issue and the version of its published standard in force today (spec §23), so a result can be tied back to it. **Render the scale from `grades` rather than hard-coding one**: PSA and TAG issue no 9.5 and BGS does, so a shared scale misrenders one of them, and a company added post-V1 appears here with no frontend change. Slow-moving reference data — the response carries `Cache-Control: public, max-age=3600`. No fees: spec §45's grading costs are user-configured economic inputs, not fetched here.
         */
        get: operations["list_grading_companies_grading_companies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report service health
         * @description Returns the liveness of the API and the version of the running application. Consults no database, network or filesystem, so it is safe to use as a readiness probe.
         */
        get: operations["read_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Report whether the API can serve traffic
         * @description Report dependency health.
         *
         *     Degrades to 503 with a body rather than raising: an orchestrator reading a
         *     500 from a readiness probe learns only that the probe is broken, whereas a
         *     503 with `checks` names the dependency that is down.
         *
         *     Every check is reported, not just the first failure: an operator fixing a
         *     deployment wants the whole list, and a probe that stops at the first problem
         *     turns one outage into two round trips.
         */
        get: operations["readiness_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalysisResponse
         * @description One analysis, as the API reports it.
         *
         *     `apps/web` generates its types from this model (ADR 0001), so the field
         *     names are a public contract.
         *
         *     Deliberately small. `session_id` is absent because it is ours and internal —
         *     the client holds a token, not a row id. Spec §57's reproducibility record is
         *     reported whole, in one nested object, rather than as fields scattered
         *     through this one: it is a single claim about how an answer was produced, and
         *     a caller checking whether an analysis can be reproduced should not have to
         *     assemble it. #35 adds the states this can hold, #104 fills `card_id`.
         */
        AnalysisResponse: {
            /**
             * Card Id
             * @description The card the user confirmed, or null before they have. Unknown until confirmation (spec §20), which is a step in the pipeline rather than a precondition of starting one.
             */
            card_id: string | null;
            /**
             * Completed At
             * @description When it reached a terminal state, or null while it has not.
             */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             * @description When the analysis was started.
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             * @description This service's identifier for the analysis.
             */
            id: string;
            /**
             * Images
             * @description Every photograph uploaded so far and spec §19's verdict on it. Empty before the first upload. This is how a `poor` verdict reaches the user, which §19 requires — a gate whose warning nothing surfaces is not a gate.
             */
            images: components["schemas"]["ImageQualityResponse"][];
            /** @description Spec §57's record: which versions of everything this answer was produced against, captured when the run claimed the analysis and immutable afterwards. */
            reproducibility: components["schemas"]["ReproducibilityResponse"];
            /**
             * Status
             * @description One of spec §65's nine states. `created` until an upload moves it. `queued` is a transport word `POST /analyses/{id}/run` answers with and is never held here.
             * @example created
             */
            status: string;
        };
        /**
         * AnalysisRunResponse
         * @description The acknowledgement `POST /analyses/{id}/run` answers with — spec §65.
         *
         *     §65 names both fields, and names the first `analysis_id` rather than `id`.
         *     Transcribed rather than tidied: this is the shape a client was told to
         *     expect, and `AnalysisResponse` is a different message about a different
         *     thing.
         */
        AnalysisRunResponse: {
            /**
             * Analysis Id
             * Format: uuid
             * @description The analysis that was queued.
             */
            analysis_id: string;
            /**
             * Status
             * @description Always `queued`. A transport word meaning 'accepted, not started' — it is not one of spec §65's nine states and no analysis ever holds it. Poll `GET /analyses/{id}` for the state the analysis is in.
             * @constant
             */
            status: "queued";
        };
        /**
         * CardConfirmationRequest
         * @description Which card the user says they are holding — spec §20, §64.
         *
         *     One field, and deliberately only one. The catalog record is the truth about
         *     what that card is, so a client that also sent a name, a set or a variant
         *     would be sending something this service must not believe (spec §55: never
         *     trust client-side card metadata). The identifier is resolved against the
         *     catalog before it is written, which is what makes it a card rather than a
         *     string the caller chose.
         */
        CardConfirmationRequest: {
            /**
             * Card Id
             * Format: uuid
             * @description The card the user confirmed, from `GET /cards/search` or `GET /cards/{id}`.
             */
            card_id: string;
        };
        /**
         * CardExternalIdResponse
         * @description One external database's identifier for this card.
         *
         *     Included because spec §10's third table is the seam that keeps catalog
         *     sources replaceable, and a support question about a wrong record is
         *     unanswerable without it. Several entries may share a `provider`: the index
         *     behind them is deliberately not unique (#23).
         */
        CardExternalIdResponse: {
            /**
             * External Id
             * @description The identifier as that provider issued it, verbatim.
             * @example bs-4-unlimited-holo
             */
            external_id: string;
            /**
             * Provider
             * @description A lowercase slug naming the source — 'manual' or 'tcgdex' in V1.
             * @example manual
             */
            provider: string;
        };
        /**
         * CardMarketResponse
         * @description The body of a successful `GET /cards/{card_id}/market`.
         */
        CardMarketResponse: {
            /**
             * Card Id
             * Format: uuid
             * @description The card these prices are for.
             */
            card_id: string;
            /**
             * Graded
             * @description Every grade every supported company can issue, in the order `GET /grading-companies` lists them and ascending within each. The full ladder every time, holes included — spec §6's price panel is read down it, and spec §39's expected value is summed over it.
             */
            graded: components["schemas"]["GradedPriceResponse"][];
            /** @description The ungraded market price, or `null` when the snapshot holds none. */
            raw: components["schemas"]["PriceResponse"] | null;
            /** @description The snapshot they were read from. Never null — see the 404 and 503. */
            snapshot: components["schemas"]["MarketSnapshotResponse"];
        };
        /**
         * CardResponse
         * @description The body of a successful `GET /cards/{id}` — spec §6's Card block.
         *
         *     `apps/web` generates its types from this model (ADR 0001), so the field
         *     names are a public contract.
         *
         *     Two absences are deliberate. `identification_confidence` belongs to an
         *     analysis, not to a catalog card, and putting it here would invite a client
         *     to read a catalog lookup as an identification. `image_front` / `image_back`
         *     are always NULL in V1 — see the module docstring and ADR 0004.
         *
         *     `metadata` is carried even though `CatalogVersionResponse` omitted its own.
         *     The two are different cases: a version's metadata records how a run went,
         *     where a card's records facts about the card that have no field yet — the set
         *     total a "4/102" is read against, for instance — and #29 names it as part of
         *     the canonical record. It generates as an untyped record, which is the honest
         *     shape for a free-form field.
         */
        CardResponse: {
            /**
             * Card Number
             * @description The number printed on the card, verbatim.
             * @example 4/102
             */
            card_number: string;
            /**
             * External Ids
             * @description Every external database identifier recorded for this card.
             */
            external_ids: components["schemas"]["CardExternalIdResponse"][];
            /**
             * Game
             * @description A lowercase slug. 'pokemon' in V1, and a field rather than a constant.
             * @example pokemon
             */
            game: string;
            /**
             * Id
             * Format: uuid
             * @description This catalog's identifier for the card. Never a provider's.
             */
            id: string;
            /**
             * Language
             * @description An ISO 639-1 code, read through the set. Japanese sets are distinct sets with their own numbering, not translations.
             * @example en
             */
            language: string;
            /**
             * Metadata
             * @description Whatever the source carried that has no field of its own.
             * @example {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Name
             * @description The card's printed name, in its own language.
             * @example Charizard
             */
            name: string;
            /**
             * Rarity
             * @description The printed rarity, where the source records one.
             * @example Rare Holo
             */
            rarity: string | null;
            set: components["schemas"]["CardSetResponse"];
            /**
             * Variant
             * @description The printing variant. Economically load-bearing: holo, reverse holo and 1st edition trade at very different prices.
             * @example unlimited-holo
             */
            variant: string | null;
        };
        /**
         * CardSearchResponse
         * @description The body of a successful `GET /cards/search`.
         *
         *     `apps/web` generates its types from this model (ADR 0001), so the field
         *     names are a public contract.
         *
         *     `total` counts every match rather than the page, so a UI can say "1-20 of
         *     137" and know when to stop. It is read in the same statement as the rows, so
         *     the two always describe one catalog.
         */
        CardSearchResponse: {
            /**
             * Cards
             * @description The matches in this window, in the catalog's total order.
             */
            cards: components["schemas"]["CardSummaryResponse"][];
            /**
             * Limit
             * @description The window size that produced `cards`.
             * @example 20
             */
            limit: number;
            /**
             * Offset
             * @description How many matches this window skipped.
             * @example 0
             */
            offset: number;
            /**
             * Total
             * @description How many cards matched in full, across every page.
             * @example 137
             */
            total: number;
        };
        /**
         * CardSetResponse
         * @description The set a card was printed in, nested rather than linked.
         *
         *     Every screen that shows a card shows its set — a card number without one
         *     identifies nothing — so a second request would be a round trip for data the
         *     first already had to join against.
         */
        CardSetResponse: {
            /**
             * Id
             * Format: uuid
             * @description This catalog's identifier for the set. Never a provider's.
             */
            id: string;
            /**
             * Metadata
             * @description Whatever the source carried that has no field of its own.
             * @example {
             *       "total_cards": 102
             *     }
             */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Name
             * @description The set's printed name, in its own language.
             * @example Base Set
             */
            name: string;
            /**
             * Release Date
             * @description The day the set went on sale, where it is known. A date, never a timestamp.
             * @example 1999-01-09
             */
            release_date: string | null;
            /**
             * Set Code
             * @description The publisher's set identifier, verbatim.
             * @example BS
             */
            set_code: string;
        };
        /**
         * CardSummaryResponse
         * @description One search result — enough to tell it apart from its neighbours.
         *
         *     Deliberately smaller than `CardResponse`. `variant` is the reason this is
         *     not merely a name and a number: holo, reverse holo and 1st edition are
         *     different cards economically, and a user who picks the wrong one is given
         *     the wrong valuation later. `external_ids` is absent because it would be a
         *     query per result for something nobody chooses between cards on, and
         *     `metadata` because it generates as an untyped record and belongs to the
         *     detail view. No thumbnail: ADR 0004 imports no card images.
         *
         *     `GET /cards/{id}` is where the rest lives; `id` is how a caller gets there.
         */
        CardSummaryResponse: {
            /**
             * Card Number
             * @description The number printed on the card, verbatim.
             * @example 4/102
             */
            card_number: string;
            /**
             * Game
             * @description A lowercase slug. 'pokemon' in V1, and a field rather than a constant.
             * @example pokemon
             */
            game: string;
            /**
             * Id
             * Format: uuid
             * @description This catalog's identifier for the card. Never a provider's.
             */
            id: string;
            /**
             * Language
             * @description An ISO 639-1 code, read through the set.
             * @example en
             */
            language: string;
            /**
             * Name
             * @description The card's printed name, in its own language.
             * @example Charizard
             */
            name: string;
            /**
             * Rarity
             * @description The printed rarity, where the source records one.
             * @example Rare Holo
             */
            rarity: string | null;
            set: components["schemas"]["CardSetResponse"];
            /**
             * Variant
             * @description The printing variant. Shown in results because it is economically load-bearing: holo, reverse holo and 1st edition trade at very different prices, so choosing between them is the point of a search.
             * @example unlimited-holo
             */
            variant: string | null;
        };
        /**
         * CatalogVersionResponse
         * @description The body of a successful `GET /catalog/version`.
         *
         *     `apps/web` generates its types from this model — see ADR 0001.
         *
         *     The record's surrogate key and its publication ordinal are deliberately
         *     absent: neither is usable by a client, and publishing the ordinal would
         *     invite one to sort on an internal key. So is `metadata`, which is free-form
         *     and would generate as an untyped record rather than a contract.
         */
        CatalogVersionResponse: {
            /**
             * Generated At
             * Format: date-time
             * @description When the source data was produced or retrieved.
             */
            generated_at: string;
            record_counts: components["schemas"]["RecordCounts"];
            /**
             * Source
             * @description A lowercase slug naming where the catalog came from.
             * @example manual
             */
            source: string;
            /**
             * Source License
             * @description The licence the source data arrived under, where one applies (ADR 0004).
             * @example MIT
             */
            source_license: string | null;
            /**
             * Source Revision
             * @description The upstream revision imported, where the source has one.
             * @example 8f2c1ab
             */
            source_revision: string | null;
            /**
             * Version
             * @description The explicit, ordered catalog identifier. Never a moving pointer (spec §31).
             * @example pokemon-catalog-seed-v0.0.0
             */
            version: string;
        };
        /**
         * ConditionVerdict
         * @description What the gate was able to say about one condition.
         *
         *     Three values rather than a boolean, because the third is the point. A gate
         *     that reported "no glare" when it had not looked for glare would be the
         *     confidently-wrong output spec §2.7 exists to forbid.
         * @enum {string}
         */
        ConditionVerdict: "clear" | "detected" | "undetermined";
        /**
         * ErrorCode
         * @description Spec §66, verbatim. The closed set of things that can go wrong.
         * @enum {string}
         */
        ErrorCode: "invalid_image" | "image_quality_failure" | "card_not_identified" | "market_data_unavailable" | "analysis_failed" | "insufficient_information" | "provider_error" | "internal_error";
        /**
         * ErrorResponse
         * @description The one error body this API produces.
         *
         *     `apps/web` generates its types from this model (ADR 0001), so the field
         *     names are a public contract.
         * @example {
         *       "code": "market_data_unavailable",
         *       "details": {
         *         "card_id": "base1-4"
         *       },
         *       "message": "No usable price is available for this card."
         *     }
         */
        ErrorResponse: {
            /** @description Machine-readable classification from the spec §66 taxonomy. */
            code: components["schemas"]["ErrorCode"];
            /**
             * Details
             * @description Optional structured context, e.g. which field was rejected.
             */
            details?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @description Human-readable summary. Safe to show a user; never contains internal detail.
             */
            message: string;
        };
        /**
         * GradedPriceResponse
         * @description What a card graded by one company at one grade is worth.
         */
        GradedPriceResponse: {
            /**
             * Company
             * @description The company's lowercase slug, as `GET /grading-companies` spells it.
             * @example psa
             */
            company: string;
            /**
             * Grade
             * @description A grade on that company's scale, spelled exactly as `GET /grading-companies` spells it. The two agree by construction.
             * @example 10
             */
            grade: string;
            /** @description `null` when this snapshot holds no price for this company and grade — which is a fact about the data, never a substituted or interpolated figure from another company. Present-and-null rather than omitted, so a client never has to tell a gap apart from a missing field. */
            price: components["schemas"]["PriceResponse"] | null;
        };
        /**
         * GradingCompaniesResponse
         * @description The body of a successful `GET /grading-companies`.
         */
        GradingCompaniesResponse: {
            /**
             * Companies
             * @description Every company the product supports, in a stable order. A company added post-V1 appends to it.
             */
            companies: components["schemas"]["GradingCompanyResponse"][];
        };
        /**
         * GradingCompanyResponse
         * @description One grading company, as a client needs to render it.
         */
        GradingCompanyResponse: {
            /**
             * Company
             * @description The company's lowercase slug. The key a graded price is stored under.
             * @example psa
             */
            company: string;
            /**
             * Display Name
             * @description What to show a user.
             * @example PSA
             */
            display_name: string;
            /**
             * Grades
             * @description Every grade this company can issue, ascending. Not shared between companies: PSA and TAG have no 9.5 and BGS does. Render from this list rather than from a hard-coded scale.
             * @example [
             *       "1",
             *       "1.5",
             *       "2",
             *       "8.5",
             *       "9",
             *       "10"
             *     ]
             */
            grades: string[];
            /** @description The published standard in force today, or `null` when no version of this company's standard has been recorded. */
            rules: components["schemas"]["GradingRulesResponse"] | null;
        };
        /**
         * GradingRulesResponse
         * @description The version of one company's published standard currently in force.
         *
         *     Spec §23's record, minus the `rules` body — that is empty in V1 by decision
         *     (#46: the published standards are the companies' copyrighted text, and what
         *     §57 needs is the identifier plus a source a human can open).
         */
        GradingRulesResponse: {
            /**
             * Effective From
             * @description When the company's published standard took effect, where the company states one. `null` where it states none — never a guess.
             * @example 2008-02-01
             */
            effective_from: string | null;
            /**
             * Effective To
             * @description When it stopped applying, or `null` while it is current. Derived from the next version's start rather than stored, so two versions of one company cannot overlap.
             * @example null
             */
            effective_to: string | null;
            /**
             * Source
             * @description Where the standard was read. A URL a human can open.
             * @example https://www.psacard.com/gradingstandards
             */
            source: string;
            /**
             * Verified On
             * Format: date
             * @description When the source was last read.
             * @example 2026-08-24
             */
            verified_on: string;
            /**
             * Version
             * @description The identifier an analysis retains — spec §57's `grading_rules_version`. No grading company publishes a version for its standard, so this one is this repository's, stamped with the date the standard was read.
             * @example psa-rules-2026-08-24
             */
            version: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description The body of a successful ``GET /health``.
         *
         *     A typed model rather than a bare dict because the OpenAPI schema is the sole
         *     source of frontend types — see ADR 0001.
         */
        HealthResponse: {
            /**
             * Application Version
             * @description Version of the running application, recorded against every analysis for reproducibility (spec §57).
             * @example 0.0.0
             */
            application_version: string;
            /**
             * Status
             * @description Liveness of the service itself. Dependencies are not consulted.
             * @constant
             */
            status: "ok";
        };
        /**
         * ImageQualityResponse
         * @description One uploaded photograph and what spec §19's gate made of it.
         */
        ImageQualityResponse: {
            /**
             * Findings
             * @description All eleven of spec §19's conditions, or empty while the gate has not run. Never a subset: a condition nobody assessed is reported `undetermined` rather than omitted.
             */
            findings: components["schemas"]["QualityFindingResponse"][];
            /**
             * Quality Score
             * @description A [0, 1] verdict, 1 being best, or null while the gate has not run. The smallest headroom any condition had, so one bad measurement is not averaged away by five good ones.
             */
            quality_score: number | null;
            /** @description Spec §19's verdict, or null while the gate has not run. `unusable` means the analysis stopped; `poor` means it went on and the user must be told. */
            quality_status: components["schemas"]["QualityStatus"] | null;
            /** @description Which view of the card this is. */
            side: components["schemas"]["ImageSide"];
        };
        /**
         * ImageResponse
         * @description One uploaded photograph, as the API reports it.
         *
         *     `apps/web` generates its types from this model (ADR 0001), so the field
         *     names are a public contract.
         *
         *     The derived columns — `normalized_uri`, `width`, `height`, `quality_score`,
         *     `quality_status` — are deliberately absent: nothing has computed one yet,
         *     and a field that is always null is an invitation to render an empty value.
         *     `analysis_status` is present because the caller has just caused the
         *     transition and would otherwise need a second request to learn whether the
         *     analysis can now be run.
         */
        ImageResponse: {
            /**
             * Analysis Id
             * Format: uuid
             * @description The analysis this photograph belongs to.
             */
            analysis_id: string;
            /**
             * Analysis Status
             * @description The analysis's state after this upload. `uploading` until every side has arrived, then `uploaded`, which is the state `POST /analyses/{id}/run` requires.
             * @example uploading
             */
            analysis_status: string;
            /**
             * Created At
             * Format: date-time
             * @description When this photograph was accepted.
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             * @description This service's identifier for the image.
             */
            id: string;
            /**
             * Mime Type
             * @description The type the file was validated as, read from its content. Never the type the request declared (spec §55).
             * @example image/jpeg
             */
            mime_type: string;
            /**
             * Sha256
             * @description A digest over the bytes that were stored — which are the uploaded bytes with their metadata removed, not the bytes as they arrived.
             */
            sha256: string;
            /**
             * Side
             * @description Which view of the card this is.
             * @example front
             */
            side: string;
        };
        /**
         * ImageSide
         * @description Which view of the card an image is — spec §11.
         *
         *     All six exist from the first migration. Only :data:`V1_SIDES` are written in
         *     V1; the other four are spec §52's guided-photography flow, which the V1
         *     image pipeline "must be compatible with". Admitting them now costs a longer
         *     CHECK constraint and saves a migration against a table holding user data.
         * @enum {string}
         */
        ImageSide: "front" | "back" | "angled_front" | "angled_back" | "surface_front" | "surface_back";
        /**
         * MarketSnapshotResponse
         * @description Which cut of the market these prices came from — spec §36.
         */
        MarketSnapshotResponse: {
            /**
             * Data Version
             * Format: date
             * @description The snapshot's date, generated from `generated_at`. **Show this beside the prices**: a dated record of a past market is honest, where the same figures presented as current are not.
             * @example 2026-08-25
             */
            data_version: string;
            /**
             * Generated At
             * Format: date-time
             * @description When the cut was taken. Every price here was stored at or before it.
             */
            generated_at: string;
            /**
             * Id
             * Format: uuid
             * @description Spec §57's `market_snapshot_id`. Pass it back as `?snapshot_id=` to read the same prices again however many ingestion runs have happened since.
             */
            id: string;
        };
        /**
         * PriceResponse
         * @description One price, with what it is currently worth believing.
         */
        PriceResponse: {
            /**
             * Amount
             * @description The amount, as an exact decimal string with two places. A string rather than a number: a JSON number is a float in most clients, and a rounding error in a figure a user is deciding money on is not acceptable. **Zero is a real price** — a card nobody will pay for — and is why an absent price is `null` rather than `0.00`.
             * @example 12.30
             */
            amount: string;
            /**
             * Currency
             * @description ISO 4217 code for `amount`.
             * @example SGD
             */
            currency: string;
            /**
             * Observed At
             * Format: date-time
             * @description When the provider saw this price. The instant `price_age_seconds` counts from.
             */
            observed_at: string;
            /**
             * Price Age Seconds
             * @description Spec §38's `price_age`: how long before this request the price was observed. Computed now rather than stored, which is why the response is not cached. A provider clock running ahead of ours reads as 0, not as a negative age.
             * @example 7200
             */
            price_age_seconds: number;
            /**
             * Price Confidence
             * @description Spec §38's `price_confidence`: how much the provider was sure of this figure, discounted for how long ago it was true. Flat at the provider's own number for a day, then falling to a floor above zero — old evidence is still evidence, and reporting it at zero would be indistinguishable from having none. The provider's undiscounted figure is deliberately not exposed: only this one is fit to show a user.
             * @example 0.86
             */
            price_confidence: number;
        };
        /**
         * QualityCondition
         * @description Spec §19's eleven conditions, in the order the specification lists them.
         *
         *     A closed list for the reason :class:`~tcg_domain.analysis.AnalysisStatus` is
         *     one: a condition nobody wrote a detector for is a condition no image can be
         *     refused for. A twelfth is a feature, and it arrives with the heuristic that
         *     decides it and the copy that explains it.
         * @enum {string}
         */
        QualityCondition: "blur" | "low_resolution" | "glare" | "poor_exposure" | "excessive_darkness" | "excessive_brightness" | "severe_perspective_distortion" | "card_partly_outside_frame" | "multiple_cards" | "sleeve_obstruction" | "insufficient_card_size";
        /**
         * QualityFindingResponse
         * @description What the gate concluded about one of spec §19's eleven conditions.
         *
         *     The measurement the gate recorded is deliberately absent. It exists so M7's
         *     model can be compared against this baseline, and a Laplacian variance is not
         *     something to put in front of somebody holding a phone; the copy that turns a
         *     condition into a sentence lives in `apps/web`.
         */
        QualityFindingResponse: {
            /**
             * @description Which of spec §19's eleven conditions this is about.
             * @example blur
             */
            condition: components["schemas"]["QualityCondition"];
            /** @description What a detected condition makes the image — `poor` or `unusable`. Null for every other verdict. Nullable rather than absent, so a reader never has to tell 'no severity' from 'field not sent'. */
            severity: components["schemas"]["QualityStatus"] | null;
            /**
             * @description `clear` if it was looked for and not found, `detected` if it was, `undetermined` if the gate could not tell. The third is a real answer, not a gap: five conditions need the card located first, which no V1 stage does yet.
             * @example clear
             */
            verdict: components["schemas"]["ConditionVerdict"];
        };
        /**
         * QualityStatus
         * @description What the image-quality gate concluded — spec §19.
         *
         *     §19 also fixes what each means for the pipeline: `unusable` stops the
         *     analysis, `poor` continues but the user must be told. `good` and
         *     `acceptable` proceed silently. The gate itself is an OpenCV heuristic in M2
         *     and a model in M7; this vocabulary does not change when it does.
         * @enum {string}
         */
        QualityStatus: "good" | "acceptable" | "poor" | "unusable";
        /**
         * ReadinessChecks
         * @description Per-dependency outcome. Further dependencies join this model as they land.
         */
        ReadinessChecks: {
            /**
             * Database
             * @description Whether the API could execute a trivial statement against PostgreSQL.
             * @enum {string}
             */
            database: "ok" | "unavailable";
            /**
             * Storage
             * @description Whether the API could reach the object store.
             * @enum {string}
             */
            storage: "ok" | "unavailable";
        };
        /**
         * ReadinessResponse
         * @description apps/web generates its types from this schema — see ADR 0001.
         */
        ReadinessResponse: {
            checks: components["schemas"]["ReadinessChecks"];
            /**
             * Status
             * @description `degraded` whenever any check failed; the response is then HTTP 503.
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * RecordCounts
         * @description How much of the catalog the run that published this version wrote.
         */
        RecordCounts: {
            /**
             * Cards
             * @description Cards the run wrote.
             * @example 22
             */
            cards: number;
            /**
             * External Ids
             * @description Provider identifiers the run wrote.
             * @example 23
             */
            external_ids: number;
            /**
             * Sets
             * @description Sets the run wrote.
             * @example 4
             */
            sets: number;
        };
        /**
         * ReproducibilityResponse
         * @description What this analysis was computed against — spec §57's record, whole.
         *
         *     Every field is read from the row rather than resolved here. That is the
         *     point of the record: the versions are the ones that were in force when the
         *     run claimed the analysis, and a value worked out at read time would describe
         *     whichever versions happen to be current now. They are written once and a
         *     database trigger refuses to change them, so re-reading this a year later
         *     answers what it answered on the day.
         *
         *     Two of §57's eight fields are not here because they are already elsewhere in
         *     the response: `analysis_id` is the analysis's own `id`, and the input image
         *     hashes are :attr:`image_sha256`.
         *
         *     A null is a documented absence, never an omission. Each field below says
         *     what its own null means, because "no model bundle exists yet" and "the field
         *     was not sent" must not look the same to a reader a year from now.
         */
        ReproducibilityResponse: {
            /**
             * Application Version
             * @description The version of this service that ran the analysis. Null until a run has claimed it — which is also the marker that no reproducibility record has been written yet. Deliberately not the version that opened the session: a session lives for days, and a deployment can happen inside one.
             * @example 0.1.0
             */
            application_version: string | null;
            /**
             * Card Database Version
             * @description The published card catalog the analysis ran against, as the identifier `GET /catalog/version` reports — captured at execution time, never a pointer to whatever is current now. Null when no run has claimed the analysis, or when no catalog version had been published when one did.
             * @example pokemon-catalog-v0.3.0
             */
            card_database_version: string | null;
            /**
             * Economic Configuration Id
             * @description The fee and cost configuration used. Always null in V1: the economic engine arrives with its own milestone.
             */
            economic_configuration_id: string | null;
            /**
             * Grading Rules Version
             * @description The grading-rule version the prediction was made under. Always null in V1: no grading rules exist yet.
             */
            grading_rules_version: string | null;
            /**
             * Image Sha256
             * @description §57's input image hashes, by side — the digest of the bytes that were *stored*, computed at upload. Empty before the first upload. A photograph cannot be replaced once an analysis has left `uploaded`, so these no longer change by the time a run records the rest of this.
             */
            image_sha256: {
                [key: string]: string;
            };
            /**
             * Market Snapshot Id
             * @description The pre-ingested market snapshot the economics were computed against. Always null in V1: market data arrives with its own milestone.
             */
            market_snapshot_id: string | null;
            /**
             * Model Bundle Version
             * @description The model bundle that produced the condition and grade predictions. Always null in V1: no model exists yet, and an explicit identifier — never `/latest/` — is what will go here when one does (spec §31).
             */
            model_bundle_version: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    start_analysis_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Too many requests from this client (spec §55). Carries `Retry-After`. Outside the spec §66 taxonomy, which has no code meaning 'throttled' — see ADR 0005. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The analysis store could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_one_analysis_analyses__analysis_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier `POST /analyses` answered with. */
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description No analysis is recorded under that identifier — for this caller. Outside the spec §66 taxonomy, which has no code meaning 'not found'. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The analysis store could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    confirm_card_analyses__analysis_id__confirm_card_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier `POST /analyses` answered with. */
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description No analysis is recorded under that identifier — for this caller — or no card is recorded under the one in the body. The first is the bare 404 `GET /analyses/{id}` answers with; the second carries the spec §66 envelope with `card_not_identified`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The analysis is not waiting for a confirmation. A bare body while it has merely not got there yet — outside the spec §66 taxonomy, which has no code meaning 'conflict' — and the §66 envelope once it has `failed`, carrying `image_quality_failure` when the gate refused the photographs and `analysis_failed` otherwise. The difference is whether trying again could ever help. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests from this client (spec §55). Carries `Retry-After`. Outside the spec §66 taxonomy — see ADR 0005. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The analysis store or the card catalog could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    upload_image_analyses__analysis_id__images_post: {
        parameters: {
            query: {
                /** @description Which view of the card this photograph is. */
                side: "front" | "back";
            };
            header?: never;
            path: {
                /** @description The identifier `POST /analyses` answered with. */
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": string;
                "image/png": string;
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageResponse"];
                };
            };
            /** @description The upload is not an image this service accepts. Always `invalid_image`; the message says which rule was broken and nothing about how the decoder failed. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No analysis is recorded under that identifier — for this caller. The same body `GET /analyses/{id}` answers with, for the same reason. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The analysis has moved past the point where its images can change. Outside the spec §66 taxonomy, which has no code meaning 'conflict'. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests from this client (spec §55, which names image uploads explicitly). Carries `Retry-After`. Outside the spec §66 taxonomy — see ADR 0005. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The analysis store or the image store could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    run_one_analysis_analyses__analysis_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The identifier `POST /analyses` answered with. */
                analysis_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisRunResponse"];
                };
            };
            /** @description No analysis is recorded under that identifier — for this caller. The same body `GET /analyses/{id}` answers with, for the same reason. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The analysis is not in a state a run may start from. Outside the spec §66 taxonomy, which has no code meaning 'conflict'. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Too many requests from this client (spec §55). Carries `Retry-After`. Outside the spec §66 taxonomy, which has no code meaning 'throttled' — see ADR 0005. */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The analysis store or the job queue could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_cards_cards_search_get: {
        parameters: {
            query?: {
                /** @description A fragment of the card's printed name. Case-insensitive. */
                text?: string | null;
                /** @description A lowercase slug — 'pokemon' in V1. */
                game?: string | null;
                /** @description An ISO 639-1 code — 'en' or 'ja' in V1. */
                language?: string | null;
                /** @description The publisher's set identifier, as printed. */
                set_code?: string | null;
                /** @description What is printed on the card. Matched as a prefix. */
                card_number?: string | null;
                /** @description A printing variant, e.g. 'reverse-holo'. */
                variant?: string | null;
                /** @description Window size. */
                limit?: number;
                /** @description How many matches to skip. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardSearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The card catalog could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_card_cards__card_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description This catalog's identifier for the card, as returned by a search. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardResponse"];
                };
            };
            /** @description No card is recorded under that identifier. `card_not_identified` from the spec §66 taxonomy; `details.card_id` says which. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The card catalog could not be reached. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_card_market_cards__card_id__market_get: {
        parameters: {
            query?: {
                /** @description Read a specific snapshot instead of the current one — spec §57's reproducibility, so a past analysis can be re-read exactly. Omit it for today's prices. */
                snapshot_id?: string | null;
            };
            header?: never;
            path: {
                /** @description This catalog's identifier for the card, as returned by a search. */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardMarketResponse"];
                };
            };
            /** @description Either no card is recorded under that identifier — `card_not_identified`, with `details.card_id` — or no snapshot was generated under the one `?snapshot_id=` named, which is `market_data_unavailable` with `details.snapshot_id`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description `market_data_unavailable` when nothing has been ingested yet, so there is no snapshot to read. `provider_error` when a store could not be reached, with `details.reason` of `market_store_unreachable` or `catalog_unreachable`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_catalog_version_catalog_version_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogVersionResponse"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The catalog could not be reached, or no version has been registered. `details.reason` says which. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_grading_companies_grading_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradingCompaniesResponse"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The grading rules could not be read. `details.reason` is `grading_rules_unreachable`. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    read_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    readiness_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Every dependency answered. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description The request failed. `code` classifies it; see spec §66. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description At least one dependency did not answer. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
