"""The one `MetaData` every table in this service is declared against.

`database/migrations/env.py` reads `target_metadata` from here, so
`alembic revision --autogenerate` compares a database against everything
declared on it — **and proposes dropping anything it cannot reach**. That is the
whole reason this module exists separately from the modules that declare tables:
the catalog is not the only domain any more, and neither domain should have to
import the other merely to share a registry.

Table modules import `metadata` from here and attach to it:

* `tcg_api.catalog.tables` — spec §10's card catalog and §57's
  `card_database_versions`.
* `tcg_api.analysis.tables` — spec §12's `analysis_sessions` / `analyses` and
  §11's `images`.
* `tcg_api.grading.tables` — spec §23's `grading_rules`.
* `tcg_api.market.tables` — spec §35's `market_providers` and
  `market_observations`.
* `tcg_api.economics.tables` — spec §46's `economic_configurations`.

This module imports nothing from `tcg_api`, and must not: the table modules
import *it*, so anything here that reached back for them would be a cycle. What
assembles the whole schema is `tcg_api.table_registry`, which imports both this
module and theirs, and is what a caller wanting a complete `MetaData` should
import. A third domain is registered there — in one place — rather than in every
caller.

The column idioms live here too, because they are conventions of the schema
rather than of any one domain — see :data:`PRINTED` in particular, which is
load-bearing rather than stylistic.
"""

from __future__ import annotations

from collections.abc import Iterable
from typing import Final

import sqlalchemy as sa

__all__ = ["NAMING_CONVENTION", "NO_METADATA", "PRINTED", "metadata", "one_of"]

# Deterministic constraint and index names, so that a future autogenerated
# revision proposes changes rather than renames. Every constraint in every table
# module is also named explicitly, to the same shape, so the migration and the
# declaration read alike.
#
# Note `ck`: the convention supplies the `ck_<table>_` prefix, and Alembic
# applies this same convention to `op.create_table`, so a `CheckConstraint` takes
# its **short** name in both places or the name renders twice.
NAMING_CONVENTION: Final = {
    "pk": "pk_%(table_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

#: Text that is ordered, compared or prefix-matched, collated by byte rather
#: than by whatever locale the server was initialised with. The local Compose
#: database runs initdb with `--locale=C` and CI's PostgreSQL service inherits
#: the image default, so a column taking the server's collation would sort — and
#: index `LIKE 'x%'` — differently in the two. Declaring it per column makes the
#: orders this schema promises mean the same thing everywhere. Japanese is
#: unaffected: it has neither case nor locale-dependent folding.
PRINTED: Final = sa.Text(collation="C")

#: An empty JSONB bag, for the `metadata` columns that carry whatever a source
#: recorded that has no column of its own.
NO_METADATA: Final = sa.text("'{}'::jsonb")


def one_of(column: str, values: Iterable[str]) -> str:
    """Render ``column IN ('a', 'b')`` from a domain vocabulary.

    Built from the enum rather than written out, so a member added to the
    vocabulary cannot be one the database silently refuses. The migration writes
    the same list as a literal — a migration is a snapshot of what was applied
    and must not change when a table module does — and the per-domain table
    tests check that the two still agree.

    Here rather than in a domain module because two domains now need it:
    `tcg_api.analysis.tables` builds four CHECK constraints with it and
    `tcg_api.market.tables` builds one. A second copy is how two spellings of
    one rule start disagreeing.
    """
    rendered = ", ".join(f"'{value}'" for value in values)
    return f"{column} IN ({rendered})"
