"""Storage keys are generated by the server and never derived from user input.

Spec §55 requires server-generated storage paths and forbids arbitrary file
access. The strongest available form of that guarantee is structural rather than
defensive: `generate_key` takes no filename argument at all, so there is no
parameter through which a client-supplied name could reach a path. The tests
below pin both halves — that the generator ignores user input by construction,
and that `StorageKey` rejects anything a hand-written key could smuggle in.

`sanitise_filename` is the deliberate escape valve: an original filename may be
worth keeping as *metadata*, and it is sanitised for that purpose alone. It is
never consulted when building a key.
"""

from __future__ import annotations

import re
from datetime import UTC, datetime

import pytest
from tcg_shared.storage import (
    MAX_KEY_LENGTH,
    InvalidStorageKey,
    StorageKey,
    generate_key,
    sanitise_filename,
)

# ---------------------------------------------------------------------------
# StorageKey validation
# ---------------------------------------------------------------------------


def test_a_plain_key_is_accepted() -> None:
    assert str(StorageKey("uploads/2026/08/17/abc-123")) == "uploads/2026/08/17/abc-123"


@pytest.mark.parametrize(
    "rejected",
    [
        pytest.param("", id="empty"),
        pytest.param("/uploads/a", id="absolute"),
        pytest.param("uploads/a/", id="trailing-slash"),
        pytest.param("uploads//a", id="empty-segment"),
        pytest.param("uploads/../secrets", id="parent-traversal"),
        pytest.param("../secrets", id="leading-traversal"),
        pytest.param("uploads/./a", id="current-directory"),
        pytest.param("..", id="bare-traversal"),
        pytest.param(r"uploads\..\secrets", id="windows-traversal"),
        pytest.param("uploads/a b", id="whitespace"),
        pytest.param("uploads/a\nb", id="newline"),
        pytest.param("uploads/a\x00b", id="null-byte"),
        pytest.param("uploads/%2e%2e/secrets", id="percent-encoded-traversal"),
        pytest.param("uploads/../../etc/passwd", id="deep-traversal"),
        pytest.param("C:/Windows/System32", id="drive-letter"),
        pytest.param("uploads/café", id="non-ascii"),
    ],
)
def test_a_key_that_could_escape_its_prefix_is_rejected(rejected: str) -> None:
    with pytest.raises(InvalidStorageKey):
        StorageKey(rejected)


def test_a_non_string_key_is_rejected() -> None:
    with pytest.raises(InvalidStorageKey):
        StorageKey(object())  # type: ignore[arg-type]


def test_an_over_long_key_is_rejected() -> None:
    """S3 caps a key at 1024 bytes; say so here rather than at the provider."""
    with pytest.raises(InvalidStorageKey):
        StorageKey("a" * (MAX_KEY_LENGTH + 1))


def test_a_key_at_the_length_limit_is_accepted() -> None:
    assert len(str(StorageKey("a" * MAX_KEY_LENGTH))) == MAX_KEY_LENGTH


def test_keys_with_the_same_value_are_equal() -> None:
    assert StorageKey("uploads/a") == StorageKey("uploads/a")


def test_a_key_is_hashable_so_it_can_index_a_mapping() -> None:
    assert {StorageKey("uploads/a"): 1}[StorageKey("uploads/a")] == 1


# ---------------------------------------------------------------------------
# generate_key
# ---------------------------------------------------------------------------


def test_a_generated_key_is_namespaced_and_date_partitioned() -> None:
    """The date prefix turns spec §54's retention sweep into a prefix scan."""
    today = datetime.now(UTC)

    key = generate_key("uploads")

    assert re.fullmatch(
        rf"uploads/{today:%Y/%m/%d}/[0-9a-f-]{{36}}",
        str(key),
    ), key


def test_generated_keys_do_not_collide() -> None:
    assert len({generate_key("uploads") for _ in range(1000)}) == 1000


def test_generate_key_accepts_no_filename() -> None:
    """The guarantee is structural: there is no parameter to smuggle a name through.

    A signature check rather than an input check, because this is the property
    that makes every traversal payload irrelevant instead of merely handled.
    """
    import inspect

    parameters = inspect.signature(generate_key).parameters

    assert list(parameters) == ["namespace"]


@pytest.mark.parametrize(
    "rejected",
    ["", "../uploads", "uploads/nested", "Uploads", "up loads", "uploads/"],
)
def test_a_malformed_namespace_is_rejected(rejected: str) -> None:
    with pytest.raises(InvalidStorageKey):
        generate_key(rejected)


# ---------------------------------------------------------------------------
# sanitise_filename — metadata only, never a path
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    ("supplied", "expected"),
    [
        ("card-front.jpg", "card-front.jpg"),
        ("../../etc/passwd", "passwd"),
        (r"..\..\windows\system32\config", "config"),
        ("/absolute/path.png", "path.png"),
        ("with spaces.jpeg", "with-spaces.jpeg"),
        ("café.jpg", "caf.jpg"),
        ("...", "unnamed"),
        ("", "unnamed"),
        ("\x00\n\t", "unnamed"),
    ],
)
def test_a_filename_is_reduced_to_a_harmless_label(supplied: str, expected: str) -> None:
    assert sanitise_filename(supplied) == expected


def test_a_sanitised_filename_is_length_capped() -> None:
    assert len(sanitise_filename("a" * 500 + ".jpg")) <= 128


def test_a_sanitised_filename_is_never_a_path() -> None:
    """Whatever arrives, the result cannot address a directory."""
    for supplied in ("a/b/c", r"a\b\c", "/", "//", "..", "./."):
        result = sanitise_filename(supplied)

        assert "/" not in result
        assert "\\" not in result
