"""Spec §10's three catalog tables, as SQLAlchemy Core.

This module is the schema's source of truth. `database/migrations/env.py` points
`target_metadata` here, so `alembic revision --autogenerate` compares a database
against these definitions, and the migration that created the tables is checked
against them by `services/api/tests/test_catalog_tables.py`.

**Core, not ORM.** The domain entities already exist in `tcg_domain.catalog` and
they are frozen dataclasses that validate on construction. Mapping them with the
ORM would mean either loosening them or maintaining a second parallel class; the
adapter in #29 reads rows and constructs entities instead, which is one direction
and no magic.

Three departures from §10's column lists, each deliberate:

* **`sets.set_code`** is added. §10 omits it, but `tcg_domain.catalog.Set`
  requires it and a card number identifies nothing without one — "4/102" is only
  a card once you know it is Base Set.
* **`cards.card_number_key`** is added, generated and stored. The
  `CardRepository.search` contract promises `card_number` matches as a prefix,
  with a user typing "25" finding a card printed "025/102". No prefix of
  "025/102" is "25", so the match runs against a normalised form; generating it
  in the database keeps it exact, immutable and indexable, and keeps
  `card_number` itself verbatim.
* **`cards.game` and `cards.language`** are kept, as §10 has them, *and* made
  unfalsifiable by a composite foreign key into `sets`. `tcg_domain.catalog.Card`
  reads both through its set precisely so the two cannot disagree; here the
  database enforces the same thing, and the search gets to filter on them
  without a join.

Every text column that is ordered, compared or prefix-matched is declared
`COLLATE "C"`. The local Compose database runs initdb with `--locale=C` and CI's
PostgreSQL service inherits the image default, so relying on the server's
collation would mean index ordering — and whether a `LIKE 'x%'` index is usable
at all — differed between the two. Declaring it per column makes the total order
`CardRepository.search` promises mean the same thing everywhere. Japanese is
unaffected: it has neither case nor locale-dependent folding.
"""

from __future__ import annotations

from typing import Final

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

__all__ = [
    "CARD_NUMBER_KEY_EXPRESSION",
    "card_external_ids",
    "cards",
    "metadata",
    "sets",
]

# Deterministic constraint and index names, so that a future autogenerated
# revision proposes changes rather than renames. Every constraint below is also
# named explicitly, to the same shape, so the migration and this file read alike.
NAMING_CONVENTION: Final = {
    "pk": "pk_%(table_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
}

metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

#: How `cards.card_number_key` is derived. Both functions are IMMUTABLE, which
#: PostgreSQL requires of a stored generated column: take everything before the
#: first "/" ("025/102" -> "025") and drop leading zeros ("025" -> "25"). A
#: number that is all zeros normalises to the empty string; that is a card that
#: does not exist, and no query looks for it.
CARD_NUMBER_KEY_EXPRESSION: Final = "ltrim(split_part(card_number, '/', 1), '0')"

# Printed text: recorded verbatim, ordered by byte. See the module docstring.
_PRINTED = sa.Text(collation="C")

_NO_METADATA: Final = sa.text("'{}'::jsonb")


sets = sa.Table(
    "sets",
    metadata,
    sa.Column(
        "id",
        sa.Uuid(),
        primary_key=True,
        comment="Ours, not a provider's. A provider's identifier is a card_external_ids row.",
    ),
    sa.Column(
        "game",
        sa.Text(),
        nullable=False,
        comment=(
            "A lowercase slug: 'pokemon' in V1. A column and never a constant — "
            "spec §73 requires One Piece, Yu-Gi-Oh! and Magic be rows of data, "
            "not a migration."
        ),
    ),
    sa.Column(
        "language",
        sa.Text(),
        nullable=False,
        comment=(
            "An ISO 639-1 code. Part of the set's identity: Japanese sets are "
            "distinct sets with their own numbering, not translations."
        ),
    ),
    sa.Column(
        "set_code",
        _PRINTED,
        nullable=False,
        comment=(
            "The publisher's set identifier, verbatim — 'SV3a'. Absent from §10's "
            "column list; the domain entity requires it."
        ),
    ),
    sa.Column(
        "name",
        _PRINTED,
        nullable=False,
        comment="The set's printed name, in its own language.",
    ),
    sa.Column(
        "release_date",
        sa.Date(),
        nullable=True,
        comment="A calendar date, never a timestamp: the day the set went on sale.",
    ),
    sa.Column(
        "metadata",
        postgresql.JSONB(),
        nullable=False,
        server_default=_NO_METADATA,
        comment="Whatever the source carried that has no column of its own.",
    ),
    sa.UniqueConstraint("game", "language", "set_code", name="uq_sets_game_language_set_code"),
    # Redundant on its own — `id` is already unique — and present only so that
    # `cards` can point a composite foreign key at it. PostgreSQL requires a
    # unique constraint covering exactly the referenced columns.
    sa.UniqueConstraint("id", "game", "language", name="uq_sets_id_game_language"),
    comment="One published set. Provider-independent, per spec §10.",
)


cards = sa.Table(
    "cards",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True, comment="Ours, not a provider's."),
    sa.Column(
        "game",
        sa.Text(),
        nullable=False,
        comment="Denormalised from the set and held there by fk_cards_set_id_game_language_sets.",
    ),
    sa.Column(
        "language",
        sa.Text(),
        nullable=False,
        comment="Denormalised from the set and held there by fk_cards_set_id_game_language_sets.",
    ),
    sa.Column("set_id", sa.Uuid(), nullable=False),
    sa.Column(
        "card_number",
        _PRINTED,
        nullable=False,
        comment="The number printed on the card, verbatim — '025/165'. Never normalised in place.",
    ),
    sa.Column(
        "card_number_key",
        _PRINTED,
        sa.Computed(CARD_NUMBER_KEY_EXPRESSION, persisted=True),
        nullable=False,
        comment=(
            "card_number reduced to its numerator without leading zeros, so that "
            "a user typing '25' matches a card printed '025/165'. Generated; "
            "never written."
        ),
    ),
    sa.Column(
        "name",
        _PRINTED,
        nullable=False,
        comment="The card's printed name, in its own language.",
    ),
    sa.Column(
        "rarity",
        _PRINTED,
        nullable=True,
        comment="The printed rarity, where the source records one.",
    ),
    sa.Column(
        "variant",
        _PRINTED,
        nullable=True,
        comment=(
            "The printing variant — '1st-edition-holo'. Economically load-bearing: "
            "holo, reverse holo and 1st edition trade at very different prices, so "
            "this is never inferred and never dropped."
        ),
    ),
    sa.Column(
        "metadata",
        postgresql.JSONB(),
        nullable=False,
        server_default=_NO_METADATA,
        comment="Whatever the source carried that has no column of its own.",
    ),
    sa.Column(
        "image_front",
        sa.Text(),
        nullable=True,
        comment=(
            "Stays NULL in V1. ADR 0004: TCGdex's MIT licence covers its "
            "compilation, not The Pokémon Company's artwork, so the only card "
            "images this product shows are the user's own uploads."
        ),
    ),
    sa.Column(
        "image_back",
        sa.Text(),
        nullable=True,
        comment="Stays NULL in V1, on the same terms as image_front. See ADR 0004.",
    ),
    sa.Column(
        "created_at",
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    ),
    sa.Column(
        "updated_at",
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    ),
    # RESTRICT rather than CASCADE: deleting a set out from under its cards is
    # never what someone meant, and the cards are what everything else references.
    sa.ForeignKeyConstraint(
        ["set_id", "game", "language"],
        ["sets.id", "sets.game", "sets.language"],
        name="fk_cards_set_id_game_language_sets",
        ondelete="RESTRICT",
    ),
    # NULLS NOT DISTINCT because `variant` is nullable, and PostgreSQL's default
    # treatment of NULL would let the same variant-less card be inserted twice.
    sa.UniqueConstraint(
        "set_id",
        "card_number",
        "variant",
        name="uq_cards_set_id_card_number_variant",
        postgresql_nulls_not_distinct=True,
    ),
    sa.Index("ix_cards_set_id", "set_id"),
    sa.Index("ix_cards_game_language_card_number_key", "game", "language", "card_number_key"),
    # Serves equality and prefix on the name. A *substring* search — which is
    # what CardQuery.text is — cannot use a B-tree and falls back to a sequential
    # scan. That is a deliberate choice at V1 catalog scale: pg_trgm would index
    # it, and `database/migrations/README.md` forbids extensions so that the
    # deployment platform stays open between ordinary PostgreSQL and Supabase.
    # Enabling it is the documented upgrade path, to be taken with measurements.
    sa.Index("ix_cards_game_language_name", "game", "language", "name"),
    comment="One canonical card. No provider column, by design — see card_external_ids.",
)


card_external_ids = sa.Table(
    "card_external_ids",
    metadata,
    sa.Column("id", sa.Uuid(), primary_key=True),
    sa.Column(
        "card_id",
        sa.Uuid(),
        sa.ForeignKey("cards.id", ondelete="CASCADE", name="fk_card_external_ids_card_id_cards"),
        nullable=False,
    ),
    sa.Column(
        "provider",
        sa.Text(),
        nullable=False,
        comment="A lowercase slug naming the source — 'manual' or 'tcgdex' in V1 (ADR 0004).",
    ),
    sa.Column(
        "external_id",
        _PRINTED,
        nullable=False,
        comment="The identifier as that provider issued it, verbatim.",
    ),
    sa.Column(
        "metadata",
        postgresql.JSONB(),
        nullable=False,
        server_default=_NO_METADATA,
        comment="Whatever the source carried that has no column of its own.",
    ),
    sa.Column(
        "created_at",
        sa.TIMESTAMP(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
    ),
    sa.UniqueConstraint(
        "card_id",
        "provider",
        "external_id",
        name="uq_card_external_ids_card_id_provider_external_id",
    ),
    # Deliberately *not* unique. A provider that does not split printing variants
    # issues one identifier for what we hold as several cards, so one
    # (provider, external_id) may legitimately name our holo row and our reverse
    # holo row both. Asserting uniqueness here would make importing such a source
    # a schema change.
    sa.Index("ix_card_external_ids_provider_external_id", "provider", "external_id"),
    comment=(
        "Spec §10: several external databases may reference the same canonical "
        "card. This table is also the seam that keeps them replaceable — dropping "
        "a source costs a DELETE here and nothing else."
    ),
)
